# Generated by Django 5.0.6 on 2026-09-01 20:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityDashboardStat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stat_key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('stat_value', models.JSONField(default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إحصائية الأمان',
                'verbose_name_plural': 'إحصائيات الأمان',
            },
        ),
        migrations.CreateModel(
            name='SystemMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_type', models.CharField(choices=[('ACTIVE_USERS', 'المستخدمون النشطون'), ('ACTIVE_CHANNELS', 'القنوات النشطة'), ('TOTAL_PATIENT', 'إجمالي المرضى'), ('MEDICAL_RECORDS', 'السجلات الطبية'), ('SECURITY_ALERTS', 'تنبيهات الأمان'), ('WAF_BLOCKS', 'حظر WAF'), ('FAILED_LOGINS', 'تسجيلات الدخول الفاشلة'), ('BIOMETRIC_LOGINS', 'دخول بيوميتري'), ('API_REQUESTS', 'طلبات API'), ('FILE_UPLOADS', 'رفع الملفات')], db_index=True, max_length=30, verbose_name='نوع المقياس')),
                ('value', models.BigIntegerField(default=0, verbose_name='القيمة')),
                ('date', models.DateField(db_index=True, verbose_name='التاريخ')),
                ('hour', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مقياس النظام',
                'verbose_name_plural': 'مقاييس النظام',
                'ordering': ['-date', '-hour'],
                'indexes': [models.Index(fields=['metric_type', '-date'], name='analytics_s_metric__99f80c_idx'), models.Index(fields=['date', 'hour'], name='analytics_s_date_f85424_idx')],
                'unique_together': {('metric_type', 'date', 'hour')},
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(db_index=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'نشاط المستخدم',
                'verbose_name_plural': 'أنشطة المستخدمين',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='analytics_u_user_id_779c80_idx'), models.Index(fields=['activity_type', '-timestamp'], name='analytics_u_activit_7a754e_idx')],
            },
        ),
    ]
