# Generated by Django 5.0.14 on 2026-09-04 20:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_channels', '0002_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='اسم التحليل')),
                ('code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='الرمز (LOINC)')),
                ('category', models.CharField(choices=[('HEMATOLOGY', 'أمراض الدم'), ('CHEMISTRY', 'كيمياء حيوية'), ('MICROBIOLOGY', 'أحياء دقيقة'), ('IMMUNOLOGY', 'مناعة'), ('URINALYSIS', 'تحليل بول'), ('COAGULATION', 'تخثر'), ('HORMONES', 'هرمونات'), ('OTHER', 'أخرى')], default='CHEMISTRY', max_length=20, verbose_name='التصنيف')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('unit', models.CharField(blank=True, help_text='مثل: mg/dL, mmol/L', max_length=50, verbose_name='الوحدة')),
                ('normal_range_min', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='الحد الأدنى الطبيعي')),
                ('normal_range_max', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='الحد الأقصى الطبيعي')),
                ('normal_range_text', models.CharField(blank=True, help_text='مثل: سلبي/إيجابي', max_length=100, verbose_name='النطاق الطبيعي (نص)')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='السعر')),
                ('turnaround_hours', models.PositiveIntegerField(default=24, verbose_name='وقت النتيجة (ساعات)')),
                ('requires_fasting', models.BooleanField(default=False, verbose_name='يتطلب صيام')),
                ('sample_type', models.CharField(blank=True, help_text='دم، بول، براز...', max_length=100, verbose_name='نوع العينة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'تحليل مختبري',
                'verbose_name_plural': 'التحاليل المختبرية',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ORDERED', 'مطلوب'), ('SAMPLE_COLLECTED', 'تم جمع العينة'), ('IN_PROGRESS', 'قيد التنفيذ'), ('COMPLETED', 'مكتمل'), ('VALIDATED', 'مصادق عليه'), ('CANCELLED', 'ملغى')], default='ORDERED', max_length=20, verbose_name='الحالة')),
                ('priority', models.CharField(choices=[('ROUTINE', 'عادي'), ('URGENT', 'مستعجل'), ('STAT', 'فوري')], default='ROUTINE', max_length=10, verbose_name='الأولوية')),
                ('clinical_notes', models.TextField(blank=True, verbose_name='ملاحظات سريرية')),
                ('fasting_confirmed', models.BooleanField(default=False, verbose_name='تأكيد الصيام')),
                ('collected_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت جمع العينة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders', to='app_channels.channel', verbose_name='القناة')),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_samples_collected', to=settings.AUTH_USER_MODEL, verbose_name='جامع العينة')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_orders_issued', to=settings.AUTH_USER_MODEL, verbose_name='الطبيب الطالب')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='patients.patient', verbose_name='المريض')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='lab.labtest', verbose_name='التحليل')),
            ],
            options={
                'verbose_name': 'طلب تحليل',
                'verbose_name_plural': 'طلبات التحاليل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='القيمة الرقمية')),
                ('text_value', models.TextField(blank=True, help_text='للنتائج غير الرقمية مثل: إيجابي/سلبي', verbose_name='القيمة النصية')),
                ('is_abnormal', models.BooleanField(default=False, verbose_name='غير طبيعي')),
                ('is_critical', models.BooleanField(default=False, verbose_name='حرج')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات الفني')),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='lab.laborder', verbose_name='الطلب')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_results_performed', to=settings.AUTH_USER_MODEL, verbose_name='فني المختبر')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_results_validated', to=settings.AUTH_USER_MODEL, verbose_name='المصادق')),
            ],
            options={
                'verbose_name': 'نتيجة تحليل',
                'verbose_name_plural': 'نتائج التحاليل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['patient', 'status'], name='lab_laborde_patient_96b1bb_idx'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['doctor', '-created_at'], name='lab_laborde_doctor__cf2b6e_idx'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['status', 'priority'], name='lab_laborde_status_38ec52_idx'),
        ),
    ]
