# pytest configuration for SecureMed
[pytest]
python_files = tests.py test_*.py *_tests.py
addopts = --verbose --tb=short --cov=apps --cov-report=term-missing --cov-report=html --ds=config.test_settings
testpaths = tests apps
