# Generated by Django 5.0.14 on 2026-09-08 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('ANDROID', 'Android'), ('WEB', 'Web'), ('IOS', 'iOS')], default='ANDROID', max_length=10, verbose_name='المنصة')),
                ('token', models.TextField(unique=True, verbose_name='رمز الإشعارات')),
                ('device_fingerprint', models.CharField(blank=True, max_length=255, verbose_name='بصمة الجهاز')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_tokens', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'رمز إشعارات',
                'verbose_name_plural': 'رموز الإشعارات',
                'indexes': [models.Index(fields=['user', 'is_active'], name='notificatio_user_id_47d48f_idx')],
            },
        ),
    ]
