# Generated by Django 5.0.6 on 2026-08-31 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('CHANNEL_INVITATION', 'دعوة لقناة'), ('CHANNEL_UPDATE', 'تحديث قناة'), ('CHANNEL_CLOSED', 'إغلاق قناة'), ('PERMISSION_GRANTED', 'منح صلاحية'), ('PERMISSION_REVOKED', 'سحب صلاحية'), ('NEW_MEDICAL_RECORD', 'سجل طبي جديد'), ('CRITICAL_PATIENT', 'حالة مريض حرجة'), ('SECURITY_ALERT', 'تنبيه أمني'), ('BIOMETRIC_ENROLLED', 'تسجيل بصمة'), ('LOGIN_ALERT', 'تنبيه دخول'), ('SYSTEM_ANNOUNCEMENT', 'إعلان نظامي'), ('MEDICATION_REMINDER', 'تذكير دواء')], db_index=True, max_length=30, verbose_name='النوع'),
        ),
    ]
