# Generated by Django 5.0.6 on 2026-09-01 20:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_channels', '0002_initial'),
        ('basins', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appointment_type', models.CharField(choices=[('INITIAL', 'كشف أول'), ('FOLLOW_UP', 'متابعة'), ('CONSULTATION', 'استشارة'), ('LAB', 'تحاليل مختبر'), ('IMAGING', 'أشعة / تصوير'), ('PROCEDURE', 'إجراء طبي'), ('EMERGENCY', 'طارئة'), ('TELEMEDICINE', 'طب عن بُعد')], default='FOLLOW_UP', max_length=20, verbose_name='نوع الموعد')),
                ('priority', models.CharField(choices=[('LOW', 'منخفضة'), ('MEDIUM', 'متوسطة'), ('HIGH', 'عالية'), ('URGENT', 'عاجلة')], default='MEDIUM', max_length=10, verbose_name='الأولوية')),
                ('status', models.CharField(choices=[('SCHEDULED', 'مجدول'), ('CONFIRMED', 'مؤكد'), ('IN_PROGRESS', 'جارٍ'), ('COMPLETED', 'مكتمل'), ('CANCELLED', 'ملغى'), ('NO_SHOW', 'لم يحضر'), ('RESCHEDULED', 'أُعيد جدولته')], default='SCHEDULED', max_length=15, verbose_name='الحالة')),
                ('scheduled_at', models.DateTimeField(verbose_name='وقت الموعد')),
                ('duration_minutes', models.PositiveIntegerField(default=30, verbose_name='المدة (دقائق)')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='المكان')),
                ('room_number', models.CharField(blank=True, max_length=50, verbose_name='رقم الغرفة')),
                ('is_virtual', models.BooleanField(default=False, verbose_name='موعد افتراضي')),
                ('virtual_link', models.URLField(blank=True, verbose_name='رابط الموعد الافتراضي')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('instructions', models.TextField(blank=True, verbose_name='تعليمات للمريض')),
                ('summary', models.TextField(blank=True, verbose_name='ملخص الموعد')),
                ('follow_up_needed', models.BooleanField(default=False, verbose_name='يحتاج متابعة')),
                ('follow_up_date', models.DateField(blank=True, null=True, verbose_name='تاريخ المتابعة')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='سبب الإلغاء')),
                ('reminder_sent_24h', models.BooleanField(default=False)),
                ('reminder_sent_1h', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('basin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='basins.basin', verbose_name='الحوض الصحي')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_appointments', to=settings.AUTH_USER_MODEL)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='app_channels.channel', verbose_name='القناة / الحالة')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('doctor', models.ForeignKey(limit_choices_to={'role__in': ['DOCTOR', 'SUPER_ADMIN', 'HOSPITAL_ADMIN']}, on_delete=django.db.models.deletion.PROTECT, related_name='doctor_appointments', to=settings.AUTH_USER_MODEL, verbose_name='الطبيب')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient', verbose_name='المريض')),
            ],
            options={
                'verbose_name': 'موعد',
                'verbose_name_plural': 'المواعيد',
                'ordering': ['scheduled_at'],
                'indexes': [models.Index(fields=['doctor', 'scheduled_at'], name='appointment_doctor__2f3cbe_idx'), models.Index(fields=['patient', 'scheduled_at'], name='appointment_patient_42b596_idx'), models.Index(fields=['status', 'scheduled_at'], name='appointment_status_eec9f6_idx'), models.Index(fields=['scheduled_at'], name='appointment_schedul_7069dc_idx')],
            },
        ),
        migrations.CreateModel(
            name='AppointmentSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(0, 'الأحد'), (1, 'الاثنين'), (2, 'الثلاثاء'), (3, 'الأربعاء'), (4, 'الخميس'), (5, 'الجمعة'), (6, 'السبت')], verbose_name='اليوم')),
                ('start_time', models.TimeField(verbose_name='وقت البدء')),
                ('end_time', models.TimeField(verbose_name='وقت الانتهاء')),
                ('slot_duration_minutes', models.PositiveIntegerField(default=30, verbose_name='مدة الموعد الواحد (دق)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_slots', to=settings.AUTH_USER_MODEL, verbose_name='الطبيب')),
            ],
            options={
                'verbose_name': 'فترة إتاحة',
                'verbose_name_plural': 'فترات الإتاحة',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('doctor', 'day_of_week', 'start_time')},
            },
        ),
    ]
