# Generated by Django 5.0.6 on 2026-08-30 22:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Basin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='اسم الحوض')),
                ('code', models.CharField(help_text='رمز قصير فريد مثل: THH-SAN-01', max_length=30, unique=True, verbose_name='الرمز')),
                ('basin_type', models.CharField(choices=[('GENERAL_HOSPITAL', 'مستشفى عام'), ('SPECIALIZED_HOSPITAL', 'مستشفى تخصصي'), ('RURAL_HOSPITAL', 'مستشفى ريفي'), ('HEALTH_CENTER', 'مركز صحي'), ('HEALTH_UNIT', 'وحدة صحية'), ('DIALYSIS_CENTER', 'مركز غسيل كلوي'), ('SPECIALIZED_CLINIC', 'مركز/عيادة تخصصية')], default='HEALTH_CENTER', help_text='نوع الحوض يحدد الوحدات المفعّلة تلقائياً', max_length=30, verbose_name='نوع الحوض')),
                ('governorate', models.CharField(blank=True, max_length=100, verbose_name='المحافظة')),
                ('directorate', models.CharField(blank=True, max_length=100, verbose_name='المديرية')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='العنوان')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('bed_capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='الطاقة الاستيعابية (أسرّة)')),
                ('enabled_modules', models.JSONField(blank=True, default=list, help_text='قائمة الوحدات المفعّلة في هذا الحوض', verbose_name='الوحدات المفعّلة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_basins', to=settings.AUTH_USER_MODEL, verbose_name='مدير الحوض')),
            ],
            options={
                'verbose_name': 'حوض صحي',
                'verbose_name_plural': 'الأحواز الصحية',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['basin_type', 'is_active'], name='basins_basi_basin_t_bb77c4_idx')],
            },
        ),
    ]
