# Generated by Django 5.0.6 on 2026-09-01 10:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceFingerprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mac_address', models.CharField(blank=True, db_index=True, help_text='MAC address (when available via network headers or client-side JS)', max_length=17, null=True)),
                ('fingerprint_hash', models.CharField(db_index=True, help_text='SHA-256 hash of combined fingerprint data', max_length=64, unique=True)),
                ('user_agent', models.TextField(blank=True, help_text='Full User-Agent string', null=True)),
                ('platform', models.CharField(blank=True, help_text='Operating system platform', max_length=100, null=True)),
                ('browser', models.CharField(blank=True, help_text='Browser name and version', max_length=100, null=True)),
                ('device_type', models.CharField(blank=True, choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('bot', 'Bot/Crawler'), ('unknown', 'Unknown')], help_text='Type of device', max_length=50, null=True)),
                ('ip_address', models.GenericIPAddressField(db_index=True, help_text='Client IP address')),
                ('ip_country', models.CharField(blank=True, help_text='Country code from IP geolocation', max_length=2, null=True)),
                ('ip_city', models.CharField(blank=True, help_text='City from IP geolocation', max_length=100, null=True)),
                ('x_forwarded_for', models.TextField(blank=True, help_text='X-Forwarded-For header chain', null=True)),
                ('x_real_ip', models.GenericIPAddressField(blank=True, help_text='X-Real-IP header', null=True)),
                ('screen_resolution', models.CharField(blank=True, help_text="Screen resolution (e.g., '1920x1080')", max_length=20, null=True)),
                ('browser_timezone', models.CharField(blank=True, help_text='Browser timezone', max_length=50, null=True)),
                ('language', models.CharField(blank=True, help_text='Browser language preference', max_length=20, null=True)),
                ('canvas_fingerprint', models.CharField(blank=True, help_text='Hash of canvas fingerprint data', max_length=64, null=True)),
                ('webrtc_ip', models.GenericIPAddressField(blank=True, help_text='IP leaked via WebRTC', null=True)),
                ('tls_fingerprint', models.CharField(blank=True, help_text='JA3 TLS fingerprint hash', max_length=64, null=True)),
                ('first_seen', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='First time this device was seen')),
                ('last_seen', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Last time this device was seen')),
                ('request_count', models.PositiveIntegerField(default=1, help_text='Total number of requests from this device')),
                ('is_suspicious', models.BooleanField(db_index=True, default=False, help_text='Flagged as suspicious by security systems')),
                ('is_blacklisted', models.BooleanField(db_index=True, default=False, help_text='Blacklisted device')),
                ('threat_score', models.PositiveSmallIntegerField(default=0, help_text='Threat score (0-100, higher = more dangerous)')),
                ('attack_signatures', models.JSONField(blank=True, default=list, help_text='List of attack signatures detected from this device')),
                ('waf_blocks', models.PositiveIntegerField(default=0, help_text='Number of WAF blocks triggered by this device')),
                ('failed_logins', models.PositiveIntegerField(default=0, help_text='Number of failed login attempts')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional fingerprint metadata')),
                ('forensic_notes', models.TextField(blank=True, help_text='Forensic analyst notes about this device')),
                ('user', models.ForeignKey(blank=True, help_text='Associated user account (if authenticated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_fingerprints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device Fingerprint',
                'verbose_name_plural': 'Device Fingerprints',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='ForensicEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_type', models.CharField(choices=[('network', 'Network Evidence'), ('application', 'Application Evidence'), ('authentication', 'Authentication Evidence'), ('injection', 'Injection Attack Evidence'), ('session', 'Session Hijacking Evidence'), ('data_exfil', 'Data Exfiltration Evidence'), ('other', 'Other Evidence')], help_text='Type of forensic evidence', max_length=50)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the evidence was collected')),
                ('evidence_data', models.JSONField(default=dict, help_text='Structured evidence data')),
                ('raw_request', models.TextField(blank=True, help_text='Raw HTTP request data')),
                ('raw_response', models.TextField(blank=True, help_text='Raw HTTP response data')),
                ('collected_by', models.CharField(default='system', help_text='Who/what collected this evidence', max_length=100)),
                ('integrity_hash', models.CharField(help_text='SHA-256 hash for evidence integrity verification', max_length=64)),
                ('incident_id', models.CharField(blank=True, db_index=True, help_text='Related incident/case ID', max_length=50, null=True)),
                ('admissibility_notes', models.TextField(blank=True, help_text='Notes on evidence admissibility and collection method')),
                ('device', models.ForeignKey(help_text='Associated device fingerprint', on_delete=django.db.models.deletion.CASCADE, related_name='forensic_evidence', to='security.devicefingerprint')),
            ],
            options={
                'verbose_name': 'Forensic Evidence',
                'verbose_name_plural': 'Forensic Evidence Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='devicefingerprint',
            index=models.Index(fields=['fingerprint_hash'], name='security_de_fingerp_d2a57a_idx'),
        ),
        migrations.AddIndex(
            model_name='devicefingerprint',
            index=models.Index(fields=['ip_address', '-last_seen'], name='security_de_ip_addr_9d5cc5_idx'),
        ),
        migrations.AddIndex(
            model_name='devicefingerprint',
            index=models.Index(fields=['mac_address'], name='security_de_mac_add_e156eb_idx'),
        ),
        migrations.AddIndex(
            model_name='devicefingerprint',
            index=models.Index(fields=['is_suspicious'], name='security_de_is_susp_c8666f_idx'),
        ),
        migrations.AddIndex(
            model_name='devicefingerprint',
            index=models.Index(fields=['threat_score'], name='security_de_threat__6ea8a1_idx'),
        ),
        migrations.AddIndex(
            model_name='forensicevidence',
            index=models.Index(fields=['device', '-timestamp'], name='security_fo_device__c2e9cc_idx'),
        ),
        migrations.AddIndex(
            model_name='forensicevidence',
            index=models.Index(fields=['evidence_type'], name='security_fo_evidenc_5f3127_idx'),
        ),
        migrations.AddIndex(
            model_name='forensicevidence',
            index=models.Index(fields=['incident_id'], name='security_fo_inciden_c1643e_idx'),
        ),
    ]
