# Generated by Django 5.0.6 on 2026-09-01 20:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(db_index=True, unique=True, verbose_name='عنوان IP')),
                ('reason', models.TextField(blank=True, verbose_name='سبب الحظر')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='ينتهي في')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'IP محظور',
                'verbose_name_plural': 'عناوين IP المحظورة',
            },
        ),
        migrations.CreateModel(
            name='BlockedDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_fingerprint', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='بصمة الجهاز')),
                ('mac_address', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='عنوان MAC')),
                ('reason', models.TextField(blank=True, verbose_name='سبب الحظر')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'جهاز محظور',
                'verbose_name_plural': 'الأجهزة المحظورة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('device_fingerprint', models.CharField(blank=True, max_length=255, verbose_name='بصمة الجهاز')),
                ('os_info', models.CharField(blank=True, max_length=255, verbose_name='نظام التشغيل')),
                ('browser_info', models.CharField(blank=True, max_length=255, verbose_name='المتصفح')),
                ('is_success', models.BooleanField(default=True, verbose_name='ناجح')),
                ('failure_reason', models.CharField(blank=True, max_length=255, verbose_name='سبب الفشل')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سجل دخول',
                'verbose_name_plural': 'تاريخ تسجيل الدخول',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DeviceRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_fingerprint', models.CharField(db_index=True, max_length=255, verbose_name='بصمة الجهاز')),
                ('mac_address', models.CharField(blank=True, max_length=100, verbose_name='عنوان MAC')),
                ('os_info', models.CharField(blank=True, max_length=255, verbose_name='نظام التشغيل')),
                ('browser_info', models.CharField(blank=True, max_length=255, verbose_name='المتصفح')),
                ('last_ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آخر عنوان IP')),
                ('is_trusted', models.BooleanField(default=False, verbose_name='موثوق')),
                ('modules_activated', models.JSONField(blank=True, default=list, verbose_name='مModules مففعل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'جهاز مسجل',
                'verbose_name_plural': 'الأجهزة المسجلة',
                'ordering': ['-last_login'],
                'unique_together': {('user', 'device_fingerprint')},
            },
        ),
    ]
