# Generated by Django 6.0.1 on 2026-09-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceregistry',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='الموقع الجغرافي'),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='الموقع الجغرافي'),
        ),
    ]
