# Generated by Django 5.0.14 on 2026-09-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_deviceverificationotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockeddevice',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='ينتهي في'),
        ),
    ]
