# Generated by Django 5.0.14 on 2026-09-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_blockeddevice_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='mac_address',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='عنوان MAC'),
        ),
    ]
