# Generated by Django 5.0.14 on 2026-09-11 16:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_login_history_mac'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceLicense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_key', models.CharField(editable=False, max_length=64, unique=True, verbose_name='مفتاح الترخيص')),
                ('status', models.CharField(choices=[('ACTIVE', 'مفعّل'), ('SUSPENDED', 'معلّق مؤقتاً'), ('REVOKED', 'ملغى')], db_index=True, default='ACTIVE', max_length=16, verbose_name='الحالة')),
                ('issued_by', models.CharField(default='system', help_text='telegram / dashboard / system', max_length=32, verbose_name='صادر بواسطة')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت التفعيل')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت إلغاء التفعيل')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='ينتهي في')),
                ('last_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر تحقق')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='ملاحظات')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='license', to='security.deviceregistry', verbose_name='الجهاز')),
            ],
            options={
                'verbose_name': 'ترخيص جهاز',
                'verbose_name_plural': 'تراخيص الأجهزة',
                'ordering': ['-issued_at'],
            },
        ),
    ]
