# Generated by Django 5.0.14 on 2026-09-11 18:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0006_devicelicense'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZTNAPendingApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_fingerprint', models.CharField(db_index=True, max_length=255, verbose_name='بصمة الجهاز')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('mac_address', models.CharField(blank=True, max_length=100, verbose_name='عنوان MAC')),
                ('os_info', models.CharField(blank=True, max_length=255, verbose_name='نظام التشغيل')),
                ('browser_info', models.CharField(blank=True, max_length=255, verbose_name='المتصفح')),
                ('is_approved', models.BooleanField(default=False, verbose_name='موافق عليه')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الموافقة')),
            ],
            options={
                'verbose_name': 'طلب ZTNA',
                'verbose_name_plural': 'طلبات ZTNA',
                'ordering': ['-created_at'],
            },
        ),
    ]
