# Generated by Django 5.0.14 on 2026-09-13 07:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_rename_patient_basin_created_idx_patients_pa_basin_i_0a03a3_idx_and_more'),
        ('security', '0007_ztnapendingapproval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakGlassAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(verbose_name='سبب الطوارئ الطبي (التبرير الإسعافي)')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='القسم الإسعافي')),
                ('status', models.CharField(choices=[('ACTIVE', 'نشط'), ('EXPIRED', 'منتهي الصلاحية'), ('REVOKED', 'ملغى يدويًا')], db_index=True, default='ACTIVE', max_length=20, verbose_name='الحالة')),
                ('activated_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='وقت التفعيل')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='وقت انتهاء الصلاحية')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإلغاء')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='وكيل المستخدم')),
                ('device_fingerprint', models.CharField(blank=True, max_length=255, verbose_name='بصمة الجهاز')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='break_glass_accesses', to='patients.patient', verbose_name='المريض')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_break_glass_events', to=settings.AUTH_USER_MODEL, verbose_name='أُلغي بواسطة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='break_glass_events', to=settings.AUTH_USER_MODEL, verbose_name='الممارس الطبي')),
            ],
            options={
                'verbose_name': 'وصول كسر الزجاج للطوارئ',
                'verbose_name_plural': 'سجلات كسر الزجاج للطوارئ',
                'ordering': ['-activated_at'],
                'indexes': [models.Index(fields=['user', 'patient', 'status'], name='security_br_user_id_ffd4e3_idx'), models.Index(fields=['patient', 'status', 'expires_at'], name='security_br_patient_caffe7_idx')],
            },
        ),
    ]
