# Generated by Django 5.0.14 on 2026-09-19 20:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0008_breakglassaccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DualCustodyApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_type', models.CharField(db_index=True, max_length=50, verbose_name='نوع العملية')),
                ('target_resource', models.CharField(max_length=255, verbose_name='المورد المستهدف')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='حمولة العملية')),
                ('justification', models.TextField(blank=True, verbose_name='التبرير')),
                ('status', models.CharField(choices=[('PENDING', 'بانتظار المراجعة'), ('APPROVED', 'معتمد'), ('REJECTED', 'مرفوض'), ('EXPIRED', 'منتهي الصلاحية'), ('EXECUTED', 'نُفِّذ')], db_index=True, default='PENDING', max_length=20, verbose_name='الحالة')),
                ('review_notes', models.TextField(blank=True, verbose_name='ملاحظات المراجعة')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='سبب الرفض')),
                ('requested_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='وقت الطلب')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت المراجعة')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='وقت انتهاء الصلاحية')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت التنفيذ')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dual_custody_approvals', to=settings.AUTH_USER_MODEL, verbose_name='المعتمد الثاني')),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dual_custody_executions', to=settings.AUTH_USER_MODEL, verbose_name='نفَّذها')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dual_custody_requests', to=settings.AUTH_USER_MODEL, verbose_name='مقدم الطلب')),
            ],
            options={
                'verbose_name': 'موافقة ثنائية',
                'verbose_name_plural': 'طلبات الموافقة الثنائية',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status', '-requested_at'], name='security_du_status_830d5a_idx'), models.Index(fields=['operation_type', 'status'], name='security_du_operati_8103e3_idx')],
            },
        ),
    ]
