package com.securemed.app.data.local

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * AES-256-GCM envelope for [LocalCache] files.
 *
 * The offline cache holds API responses verbatim — patient names, diagnoses,
 * prescriptions — in the app's private directory. Private storage is not a
 * confidentiality control on a rooted device, in an ADB backup, or once
 * another app escapes its sandbox, so the bytes are encrypted with a key that
 * never leaves the hardware-backed keystore.
 *
 * File layout (mirrors the backend's `SMEDF1` media envelope so the two are
 * recognisable side by side):
 *
 *     "SMEDC1" | iv (12 bytes) | ciphertext + GCM tag (16 bytes)
 *
 * The magic prefix is what makes the migration in [LocalCache.load] possible:
 * a file written by an older build has no prefix, so it can be read once as
 * plaintext and immediately rewritten encrypted.
 *
 * The key is deliberately *not* `setUserAuthenticationRequired(true)`. Dose
 * reminders are re-armed by a boot receiver and fired by AlarmManager while
 * nobody is looking at the screen; a key that demands a fresh biometric would
 * silently kill that path. The keys that do require user presence are the
 * SQLCipher passphrase holder and the biometric signing key, not this one.
 */
object CacheCrypto {

    private const val KEYSTORE_PROVIDER = "AndroidKeyStore"
    private const val KEY_ALIAS = "securemed_cache_key_v1"
    private const val TRANSFORMATION = "AES/GCM/NoPadding"
    private const val TAG_BITS = 128
    private const val IV_BYTES = 12

    /** "SMEDC1" — cache envelope, version 1. */
    private val MAGIC = byteArrayOf(0x53, 0x4D, 0x45, 0x44, 0x43, 0x31)

    private val HEADER_BYTES = MAGIC.size + IV_BYTES

    /** True when [bytes] carries this envelope, i.e. is not a legacy plaintext file. */
    fun looksEncrypted(bytes: ByteArray): Boolean {
        if (bytes.size <= HEADER_BYTES) return false
        for (i in MAGIC.indices) {
            if (bytes[i] != MAGIC[i]) return false
        }
        return true
    }

    /**
     * Returns the sealed envelope, or null when the keystore is unusable.
     * Callers must treat null as "do not persist": writing the plaintext
     * instead would defeat the entire point of this class.
     */
    fun encrypt(plaintext: String): ByteArray? {
        return try {
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(Cipher.ENCRYPT_MODE, secretKey() ?: return null)
            // GCM keys in AndroidKeyStore reject a caller-supplied IV
            // (setRandomizedEncryptionRequired defaults to true), so the IV is
            // generated by the provider and read back here.
            val iv = cipher.iv
            if (iv == null || iv.size != IV_BYTES) return null
            val body = cipher.doFinal(plaintext.toByteArray(Charsets.UTF_8))
            MAGIC + iv + body
        } catch (_: Throwable) {
            null
        }
    }

    /**
     * Returns the plaintext, or null when the file is not a valid envelope,
     * the tag does not verify, or the key is gone (app data restored onto a
     * different device, keystore reset by a system update). Null is always
     * recoverable: the cache is a copy of data the server still has.
     */
    fun decrypt(bytes: ByteArray): String? {
        if (!looksEncrypted(bytes)) return null
        return try {
            val iv = bytes.copyOfRange(MAGIC.size, HEADER_BYTES)
            val body = bytes.copyOfRange(HEADER_BYTES, bytes.size)
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(
                Cipher.DECRYPT_MODE,
                existingKey() ?: return null,
                GCMParameterSpec(TAG_BITS, iv)
            )
            String(cipher.doFinal(body), Charsets.UTF_8)
        } catch (_: Throwable) {
            null
        }
    }

    private fun secretKey(): SecretKey? = existingKey() ?: generateKey()

    private fun existingKey(): SecretKey? = try {
        val keyStore = KeyStore.getInstance(KEYSTORE_PROVIDER).apply { load(null) }
        (keyStore.getEntry(KEY_ALIAS, null) as? KeyStore.SecretKeyEntry)?.secretKey
    } catch (_: Throwable) {
        null
    }

    private fun generateKey(): SecretKey? = try {
        val spec = KeyGenParameterSpec.Builder(
            KEY_ALIAS,
            KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT
        )
            .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
            .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
            .setKeySize(256)
            .build()
        KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, KEYSTORE_PROVIDER)
            .apply { init(spec) }
            .generateKey()
    } catch (_: Throwable) {
        null
    }
}
