# Generated by Django 5.0.6 on 2026-09-01 20:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basins', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('OWNER', 'مالك القناة'), ('MODERATOR', 'مشرف'), ('EDITOR', 'محرر'), ('CONTRIBUTOR', 'مساهم'), ('VIEWER', 'مشاهد')], default='VIEWER', max_length=20, verbose_name='الدور المقترح')),
                ('status', models.CharField(choices=[('PENDING', 'معلق'), ('ACCEPTED', 'مقبول'), ('REJECTED', 'مرفوض'), ('EXPIRED', 'منتهي')], default='PENDING', max_length=10, verbose_name='الحالة')),
                ('message', models.TextField(blank=True, verbose_name='رسالة')),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'دعوة',
                'verbose_name_plural': 'الدعوات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChannelMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('OWNER', 'مالك القناة'), ('MODERATOR', 'مشرف'), ('EDITOR', 'محرر'), ('CONTRIBUTOR', 'مساهم'), ('VIEWER', 'مشاهد')], default='VIEWER', max_length=20, verbose_name='الدور')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تنتهي في')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'عضوية',
                'verbose_name_plural': 'العضويات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChannelMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField(max_length=4000, verbose_name='نص الرسالة')),
                ('is_edited', models.BooleanField(default=False, verbose_name='معدلة')),
                ('is_system', models.BooleanField(default=False, verbose_name='رسالة نظام')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'رسالة قناة',
                'verbose_name_plural': 'رسائل القنوات',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='اسم القناة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('channel_type', models.CharField(choices=[('EMERGENCY', 'حالة طارئة'), ('INPATIENT', 'مريض مقيم'), ('OUTPATIENT', 'مريض خارجي'), ('CONSULTATION', 'استشارة'), ('FOLLOW_UP', 'متابعة')], default='OUTPATIENT', max_length=20, verbose_name='نوع القناة')),
                ('status', models.CharField(choices=[('ACTIVE', 'نشط'), ('ARCHIVED', 'مؤرشف'), ('CLOSED', 'مغلق')], default='ACTIVE', max_length=10, verbose_name='الحالة')),
                ('is_encrypted', models.BooleanField(default=True)),
                ('priority', models.CharField(choices=[('LOW', 'منخفضة'), ('MEDIUM', 'متوسطة'), ('HIGH', 'عالية'), ('URGENT', 'عاجلة')], default='MEDIUM', max_length=10, verbose_name='الأولوية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('basin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='channels', to='basins.basin', verbose_name='الحوض الصحي')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_channels', to=settings.AUTH_USER_MODEL, verbose_name='مالك القناة')),
            ],
            options={
                'verbose_name': 'قناة',
                'verbose_name_plural': 'القنوات',
                'ordering': ['-created_at'],
            },
        ),
    ]
