# Generated by Django 5.0.6 on 2026-09-01 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_channels', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='patients.patient', verbose_name='المريض'),
        ),
        migrations.AddField(
            model_name='channelinvitation',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='app_channels.channel'),
        ),
        migrations.AddField(
            model_name='channelinvitation',
            name='invited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channelinvitation',
            name='invitee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channelmembership',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='app_channels.channel', verbose_name='القناة'),
        ),
        migrations.AddField(
            model_name='channelmembership',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_memberships', to=settings.AUTH_USER_MODEL, verbose_name='مُ granted بواسطة'),
        ),
        migrations.AddField(
            model_name='channelmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_memberships', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddField(
            model_name='channelmessage',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app_channels.channel', verbose_name='القناة'),
        ),
        migrations.AddField(
            model_name='channelmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_messages', to=settings.AUTH_USER_MODEL, verbose_name='المرسل'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['status', 'priority'], name='app_channel_status_88918f_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['owner'], name='app_channel_owner_i_ada1d8_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['patient'], name='app_channel_patient_3cb271_idx'),
        ),
        migrations.AddIndex(
            model_name='channelmembership',
            index=models.Index(fields=['channel', 'user', 'is_active'], name='app_channel_channel_d597bc_idx'),
        ),
        migrations.AddIndex(
            model_name='channelmembership',
            index=models.Index(fields=['user', 'is_active'], name='app_channel_user_id_f99335_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='channelmembership',
            unique_together={('channel', 'user')},
        ),
        migrations.AddIndex(
            model_name='channelmessage',
            index=models.Index(fields=['channel', 'created_at'], name='app_channel_channel_9bb9f0_idx'),
        ),
        migrations.AddIndex(
            model_name='channelmessage',
            index=models.Index(fields=['sender'], name='app_channel_sender__8be8da_idx'),
        ),
    ]
