# Generated by Django 5.0.6 on 2026-08-28 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='patients.patient', verbose_name='المريض'),
        ),
        migrations.AddField(
            model_name='channelinvitation',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='channels.channel'),
        ),
        migrations.AddField(
            model_name='channelinvitation',
            name='invited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channelinvitation',
            name='invitee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channelmembership',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='channels.channel', verbose_name='القناة'),
        ),
        migrations.AddField(
            model_name='channelmembership',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_memberships', to=settings.AUTH_USER_MODEL, verbose_name='مُ granted بواسطة'),
        ),
        migrations.AddField(
            model_name='channelmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_memberships', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['status', 'priority'], name='channels_ch_status_b953ca_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['owner'], name='channels_ch_owner_i_13d335_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['patient'], name='channels_ch_patient_1d4479_idx'),
        ),
        migrations.AddIndex(
            model_name='channelmembership',
            index=models.Index(fields=['channel', 'user', 'is_active'], name='channels_ch_channel_ab1ff1_idx'),
        ),
        migrations.AddIndex(
            model_name='channelmembership',
            index=models.Index(fields=['user', 'is_active'], name='channels_ch_user_id_8b2b0e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='channelmembership',
            unique_together={('channel', 'user')},
        ),
    ]
