# Generated by Django 5.0.6 on 2026-08-30 14:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField(max_length=4000, verbose_name='نص الرسالة')),
                ('is_edited', models.BooleanField(default=False, verbose_name='معدلة')),
                ('is_system', models.BooleanField(default=False, verbose_name='رسالة نظام')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='channels.channel', verbose_name='القناة')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_messages', to=settings.AUTH_USER_MODEL, verbose_name='المرسل')),
            ],
            options={
                'verbose_name': 'رسالة قناة',
                'verbose_name_plural': 'رسائل القنوات',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['channel', 'created_at'], name='channels_ch_channel_2926df_idx'), models.Index(fields=['sender'], name='channels_ch_sender__775645_idx')],
            },
        ),
    ]
