# Generated by Django 5.0.6 on 2026-09-01 20:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('LOGIN_SUCCESS', 'تسجيل دخول ناجح'), ('LOGIN_FAILED', 'فشل تسجيل الدخول'), ('LOGOUT', 'تسجيل خروج'), ('BIOMETRIC_LOGIN_SUCCESS', 'دخول بيوميتري ناجح'), ('BIOMETRIC_ENROLLMENT', 'تسجيل بصمة'), ('BIOMETRIC_CHALLENGE_REQUESTED', 'طلب تحدي بيوميتري'), ('BIOMETRIC_REVOKED', 'إلغاء بصمة'), ('PASSWORD_CHANGED', 'تغيير كلمة المرور'), ('PERMISSION_GRANTED', 'منح صلاحية'), ('PERMISSION_MODIFIED', 'تعديل صلاحية'), ('PERMISSION_REVOKED', 'سحب صلاحية'), ('MEMBERSHIP_CANCELLED', 'إلغاء عضوية'), ('CHANNEL_CREATED', 'إنشاء قناة'), ('CHANNEL_CLOSED', 'إغلاق قناة'), ('CHANNEL_MESSAGE_SENT', 'إرسال رسالة في قناة'), ('PATIENT_DATA_ACCESSED', 'الوصول لبيانات مريض'), ('MEDICAL_RECORD_CREATED', 'إنشاء سجل طبي'), ('PORT_SCAN_EXECUTED', 'تنفيذ مسح منافذ'), ('VULN_SCAN_EXECUTED', 'تنفيذ فحص ثغرات'), ('WAF_BLOCKED', 'حظر WAF'), ('INVITATION_SENT', 'إرسال دعوة'), ('INVITATION_ACCEPTED', 'قبول دعوة'), ('INVITATION_REJECTED', 'رفض دعوة'), ('USER_DEACTIVATED', 'إلغاء تفعيل مستخدم'), ('MFA_ENABLED', 'تفعيل التحقق بخطوتين'), ('MFA_DISABLED', 'تعطيل التحقق بخطوتين'), ('MFA_LOGIN_SUCCESS', 'دخول ناجح بالتحقق بخطوتين'), ('MFA_LOGIN_FAILED', 'فشل التحقق بخطوتين'), ('PASSWORD_RESET_REQUESTED', 'طلب استعادة كلمة المرور'), ('PASSWORD_RESET_COMPLETED', 'إتمام استعادة كلمة المرور'), ('DEVICE_BLOCKED', 'حظر جهاز'), ('SUSPICIOUS_ACTIVITY', 'نشاط مشبوه'), ('SESSION_HIJACK_DETECTED', 'اكتشاف سرقة جلسة'), ('DATA_EXPORT', 'تصدير بيانات'), ('BULK_DELETE', 'حذف جماعي'), ('CONFIG_CHANGED', 'تغيير إعدادات'), ('BACKUP_CREATED', 'إنشاء نسخة احتياطية'), ('BACKUP_RESTORED', 'استعادة نسخة احتياطية'), ('FILE_UPLOADED', 'رفع ملف'), ('FILE_DOWNLOADED', 'تحميل ملف'), ('DATA_CREATED', 'إنشاء بيانات'), ('DATA_MODIFIED', 'تعديل بيانات'), ('DATA_DELETED', 'حذف بيانات')], db_index=True, max_length=40, verbose_name='نوع الحدث')),
                ('severity', models.CharField(choices=[('INFO', 'معلومة'), ('WARNING', 'تحذير'), ('CRITICAL', 'حرج')], default='INFO', max_length=10, verbose_name='الخطورة')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('path', models.CharField(blank=True, max_length=255, verbose_name='المسار')),
                ('method', models.CharField(blank=True, max_length=10, verbose_name='الطريقة')),
                ('mac_address', models.CharField(blank=True, max_length=100, verbose_name='عنوان MAC')),
                ('device_fingerprint', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='بصمة الجهاز')),
                ('hostname', models.CharField(blank=True, max_length=255, verbose_name='اسم الجهاز')),
                ('os_info', models.CharField(blank=True, max_length=255, verbose_name='نظام التشغيل')),
                ('browser_info', models.CharField(blank=True, max_length=255, verbose_name='المتصفح')),
                ('screen_resolution', models.CharField(blank=True, max_length=50, verbose_name='دقة الشاشة')),
                ('timezone_offset', models.CharField(blank=True, max_length=50, verbose_name='فرق التوقيت')),
                ('language', models.CharField(blank=True, max_length=50, verbose_name='اللغة')),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='معرف الجلسة')),
                ('geo_location', models.CharField(blank=True, max_length=255, verbose_name='الموقع الجغرافي')),
                ('risk_score', models.FloatField(default=0.0, verbose_name='درجة المخاطرة')),
                ('details', models.JSONField(default=dict, verbose_name='التفاصيل')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='الوقت')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل تدقيق',
                'verbose_name_plural': 'سجلات التدقيق',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_type', '-timestamp'], name='audit_audit_event_t_47b5ec_idx'), models.Index(fields=['user', '-timestamp'], name='audit_audit_user_id_ea8c9f_idx'), models.Index(fields=['severity', '-timestamp'], name='audit_audit_severit_34f2e8_idx')],
            },
        ),
    ]
