# Generated by Django 5.0.6 on 2026-08-28 03:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('LOGIN_SUCCESS', 'تسجيل دخول ناجح'), ('LOGIN_FAILED', 'فشل تسجيل الدخول'), ('LOGOUT', 'تسجيل خروج'), ('BIOMETRIC_LOGIN_SUCCESS', 'دخول بيوميتري ناجح'), ('BIOMETRIC_ENROLLMENT', 'تسجيل بصمة'), ('BIOMETRIC_CHALLENGE_REQUESTED', 'طلب تحدي بيوميتري'), ('BIOMETRIC_REVOKED', 'إلغاء بصمة'), ('PASSWORD_CHANGED', 'تغيير كلمة المرور'), ('PERMISSION_GRANTED', 'منح صلاحية'), ('PERMISSION_MODIFIED', 'تعديل صلاحية'), ('PERMISSION_REVOKED', 'سحب صلاحية'), ('MEMBERSHIP_CANCELLED', 'إلغاء عضوية'), ('CHANNEL_CREATED', 'إنشاء قناة'), ('CHANNEL_CLOSED', 'إغلاق قناة'), ('PATIENT_DATA_ACCESSED', 'الوصول لبيانات مريض'), ('MEDICAL_RECORD_CREATED', 'إنشاء سجل طبي'), ('PORT_SCAN_EXECUTED', 'تنفيذ مسح منافذ'), ('VULN_SCAN_EXECUTED', 'تنفيذ فحص ثغرات'), ('WAF_BLOCKED', 'حظر WAF'), ('INVITATION_SENT', 'إرسال دعوة'), ('INVITATION_ACCEPTED', 'قبول دعوة'), ('INVITATION_REJECTED', 'رفض دعوة'), ('USER_DEACTIVATED', 'إلغاء تفعيل مستخدم')], db_index=True, max_length=40, verbose_name='نوع الحدث')),
                ('severity', models.CharField(choices=[('INFO', 'معلومة'), ('WARNING', 'تحذير'), ('CRITICAL', 'حرج')], default='INFO', max_length=10, verbose_name='الخطورة')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('path', models.CharField(blank=True, max_length=255, verbose_name='المسار')),
                ('method', models.CharField(blank=True, max_length=10, verbose_name='الطريقة')),
                ('details', models.JSONField(default=dict, verbose_name='التفاصيل')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='الوقت')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل تدقيق',
                'verbose_name_plural': 'سجلات التدقيق',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_type', '-timestamp'], name='audit_audit_event_t_47b5ec_idx'), models.Index(fields=['user', '-timestamp'], name='audit_audit_user_id_ea8c9f_idx'), models.Index(fields=['severity', '-timestamp'], name='audit_audit_severit_34f2e8_idx')],
            },
        ),
    ]
