# Generated by Django 5.0.14 on 2026-09-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='hash',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, verbose_name='التوقيع التشفيري'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='previous_hash',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, verbose_name='توقيع السجل السابق'),
        ),
    ]
