# Generated by Django 5.0.6 on 2026-08-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='event_type',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'تسجيل دخول ناجح'), ('LOGIN_FAILED', 'فشل تسجيل الدخول'), ('LOGOUT', 'تسجيل خروج'), ('BIOMETRIC_LOGIN_SUCCESS', 'دخول بيوميتري ناجح'), ('BIOMETRIC_ENROLLMENT', 'تسجيل بصمة'), ('BIOMETRIC_CHALLENGE_REQUESTED', 'طلب تحدي بيوميتري'), ('BIOMETRIC_REVOKED', 'إلغاء بصمة'), ('PASSWORD_CHANGED', 'تغيير كلمة المرور'), ('PERMISSION_GRANTED', 'منح صلاحية'), ('PERMISSION_MODIFIED', 'تعديل صلاحية'), ('PERMISSION_REVOKED', 'سحب صلاحية'), ('MEMBERSHIP_CANCELLED', 'إلغاء عضوية'), ('CHANNEL_CREATED', 'إنشاء قناة'), ('CHANNEL_CLOSED', 'إغلاق قناة'), ('CHANNEL_MESSAGE_SENT', 'إرسال رسالة في قناة'), ('PATIENT_DATA_ACCESSED', 'الوصول لبيانات مريض'), ('MEDICAL_RECORD_CREATED', 'إنشاء سجل طبي'), ('PORT_SCAN_EXECUTED', 'تنفيذ مسح منافذ'), ('VULN_SCAN_EXECUTED', 'تنفيذ فحص ثغرات'), ('WAF_BLOCKED', 'حظر WAF'), ('INVITATION_SENT', 'إرسال دعوة'), ('INVITATION_ACCEPTED', 'قبول دعوة'), ('INVITATION_REJECTED', 'رفض دعوة'), ('USER_DEACTIVATED', 'إلغاء تفعيل مستخدم'), ('MFA_ENABLED', 'تفعيل التحقق بخطوتين'), ('MFA_DISABLED', 'تعطيل التحقق بخطوتين'), ('MFA_LOGIN_SUCCESS', 'دخول ناجح بالتحقق بخطوتين'), ('MFA_LOGIN_FAILED', 'فشل التحقق بخطوتين')], db_index=True, max_length=40, verbose_name='نوع الحدث'),
        ),
    ]
