# Generated by Django 5.0.6 on 2026-09-01 20:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='اسم الشركة')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='رقم الهاتف')),
                ('api_endpoint', models.URLField(blank=True, verbose_name='رابط التخاطب الآلي (API)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'شركة تأمين',
                'verbose_name_plural': 'شركات التأمين',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='المبلغ الإجمالي')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='الخصم')),
                ('insurance_covered', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='تغطية التأمين')),
                ('patient_payable', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='المبلغ المستحق على المريض')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('PENDING_INSURANCE', 'بانتظار موافقة التأمين'), ('UNPAID', 'غير مدفوعة'), ('PARTIAL', 'مدفوعة جزئياً'), ('PAID', 'مدفوعة'), ('CANCELLED', 'ملغاة')], default='DRAFT', max_length=50, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='patients.patient')),
            ],
            options={
                'verbose_name': 'فاتورة',
                'verbose_name_plural': 'الفواتير',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255, verbose_name='الوصف')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الإجمالي')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='PatientInsurance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policy_number', models.CharField(max_length=100, verbose_name='رقم البوليصة')),
                ('coverage_percentage', models.DecimalField(decimal_places=2, default=100.0, max_digits=5, verbose_name='نسبة التغطية')),
                ('expiry_date', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('is_valid', models.BooleanField(default=True, verbose_name='صالح')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_policies', to='patients.patient')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.insuranceprovider')),
            ],
            options={
                'verbose_name': 'تأمين المريض',
                'verbose_name_plural': 'تأمينات المرضى',
            },
        ),
    ]
