# Generated by Django 5.0.14 on 2026-09-04 20:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ المطالب به')),
                ('approved_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='المبلغ الموافق عليه')),
                ('status', models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('APPROVED', 'موافق عليها'), ('REJECTED', 'مرفوضة'), ('PARTIAL', 'موافق عليها جزئياً')], default='PENDING', max_length=50, verbose_name='حالة المطالبة')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, verbose_name='سبب الرفض')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_claim', to='billing.invoice')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.patientinsurance')),
            ],
            options={
                'verbose_name': 'مطالبة تأمين',
                'verbose_name_plural': 'مطالبات التأمين',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(max_length=255, unique=True, verbose_name='رقم العملية')),
                ('gateway', models.CharField(default='STRIPE', max_length=50, verbose_name='بوابة الدفع')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ المدفوع')),
                ('currency', models.CharField(default='SAR', max_length=10, verbose_name='العملة')),
                ('status', models.CharField(choices=[('SUCCESS', 'ناجح'), ('FAILED', 'فاشل'), ('PENDING', 'معلق')], default='PENDING', max_length=50, verbose_name='حالة الدفع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='billing.invoice')),
            ],
            options={
                'verbose_name': 'عملية دفع',
                'verbose_name_plural': 'عمليات الدفع',
            },
        ),
    ]
