# Generated by Django 5.0.6 on 2026-09-01 20:21

import apps.patients.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_channels', '0001_initial'),
        ('basins', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('_full_name', models.TextField(db_column='full_name', verbose_name='الاسم الكامل المشفر')),
                ('_national_id', models.TextField(blank=True, db_column='national_id', verbose_name='رقم الهوية المشفر')),
                ('_phone', models.TextField(blank=True, db_column='phone', verbose_name='الهاتف المشفر')),
                ('_address', models.TextField(blank=True, db_column='address', verbose_name='العنوان المشفر')),
                ('date_of_birth', models.DateField(verbose_name='تاريخ الميلاد')),
                ('gender', models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثى'), ('O', 'أخرى')], max_length=1, verbose_name='الجنس')),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='فصيلة الدم')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='الطول (سم)')),
                ('weight', models.PositiveIntegerField(blank=True, null=True, verbose_name='الوزن (كجم)')),
                ('allergies', models.TextField(blank=True, verbose_name='الحساسية')),
                ('chronic_conditions', models.TextField(blank=True, verbose_name='الأمراض المزمنة')),
                ('current_medications', models.TextField(blank=True, verbose_name='الأدوية الحالية')),
                ('_emergency_contact', models.TextField(blank=True, db_column='emergency_contact', verbose_name='جهة الاتصال الطارئة المشفرة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('basin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='basins.basin', verbose_name='الحوض الصحي')),
            ],
            options={
                'verbose_name': 'مريض',
                'verbose_name_plural': 'المرضى',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_type', models.CharField(choices=[('DIAGNOSIS', 'تشخيص'), ('PRESCRIPTION', 'وصفة طبية'), ('LAB_ORDER', 'طلب تحاليل'), ('LAB_RESULT', 'نتيجة تحاليل'), ('IMAGING', 'تصوير طبي'), ('NOTES', 'ملاحظات'), ('VITALS', 'علامات حيوية'), ('PROCEDURE', 'إجراء طبي')], max_length=20, verbose_name='نوع السجل')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('_content', models.TextField(db_column='content', verbose_name='المحتوى المشفر')),
                ('blood_pressure_systolic', models.PositiveIntegerField(blank=True, null=True)),
                ('blood_pressure_diastolic', models.PositiveIntegerField(blank=True, null=True)),
                ('heart_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('respiratory_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('oxygen_saturation', models.PositiveIntegerField(blank=True, null=True)),
                ('is_critical', models.BooleanField(default=False, verbose_name='حرج')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='app_channels.channel', verbose_name='القناة المرتبطة')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_records', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'سجل طبي',
                'verbose_name_plural': 'السجلات الطبية',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['channel', 'record_type'], name='patients_me_channel_31bb6e_idx'), models.Index(fields=['is_critical'], name='patients_me_is_crit_0f551c_idx')],
            },
        ),
        migrations.CreateModel(
            name='MedicalFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=500, upload_to=apps.patients.models.medical_file_upload_path, validators=[apps.patients.models.validate_file_extension, apps.patients.models.validate_file_size], verbose_name='الملف')),
                ('original_filename', models.CharField(max_length=255, verbose_name='اسم الملف الأصلي')),
                ('file_type', models.CharField(choices=[('XRAY', 'أشعة سينية'), ('MRI', 'رنين مغناطيسي'), ('CT_SCAN', 'تصوير مقطعي'), ('ULTRASOUND', 'موجات صوتية'), ('LAB_REPORT', 'تقرير مختبر'), ('DOCUMENT', 'مستند'), ('OTHER', 'أخرى')], max_length=20, verbose_name='نوع الملف')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='حجم الملف (بايت)')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='نوع MIME')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('study_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الفحص')),
                ('body_part', models.CharField(blank=True, max_length=100, verbose_name='العضو المفحوص')),
                ('modality', models.CharField(blank=True, max_length=50, verbose_name='طريقة الفحص')),
                ('is_critical', models.BooleanField(default=False, verbose_name='حرج')),
                ('access_count', models.PositiveIntegerField(default=0, verbose_name='عدد الوصول')),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_files', to='app_channels.channel', verbose_name='قناة الحالة')),
                ('last_accessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_accessed_files', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_medical_files', to=settings.AUTH_USER_MODEL, verbose_name='رُفع بواسطة')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_files', to='patients.patient', verbose_name='المريض')),
            ],
            options={
                'verbose_name': 'ملف طبي',
                'verbose_name_plural': 'الملفات الطبية',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['channel', 'file_type'], name='patients_me_channel_134cdb_idx'), models.Index(fields=['patient', '-created_at'], name='patients_me_patient_2d9b89_idx'), models.Index(fields=['is_critical'], name='patients_me_is_crit_d962d9_idx')],
            },
        ),
    ]
