# Generated by Django 5.0.6 on 2026-08-28 12:40

import apps.patients.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=500, upload_to=apps.patients.models.medical_file_upload_path, validators=[apps.patients.models.validate_file_extension, apps.patients.models.validate_file_size], verbose_name='الملف')),
                ('original_filename', models.CharField(max_length=255, verbose_name='اسم الملف الأصلي')),
                ('file_type', models.CharField(choices=[('XRAY', 'أشعة سينية'), ('MRI', 'رنين مغناطيسي'), ('CT_SCAN', 'تصوير مقطعي'), ('ULTRASOUND', 'موجات صوتية'), ('LAB_REPORT', 'تقرير مختبر'), ('DOCUMENT', 'مستند'), ('OTHER', 'أخرى')], max_length=20, verbose_name='نوع الملف')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='حجم الملف (بايت)')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='نوع MIME')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('study_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الفحص')),
                ('body_part', models.CharField(blank=True, max_length=100, verbose_name='العضو المفحوص')),
                ('modality', models.CharField(blank=True, max_length=50, verbose_name='طريقة الفحص')),
                ('is_critical', models.BooleanField(default=False, verbose_name='حرج')),
                ('access_count', models.PositiveIntegerField(default=0, verbose_name='عدد الوصول')),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_files', to='channels.channel', verbose_name='القناة')),
                ('last_accessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_accessed_files', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_files', to='patients.patient', verbose_name='المريض')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_medical_files', to=settings.AUTH_USER_MODEL, verbose_name='رُفع بواسطة')),
            ],
            options={
                'verbose_name': 'ملف طبي',
                'verbose_name_plural': 'الملفات الطبية',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['channel', 'file_type'], name='patients_me_channel_134cdb_idx'), models.Index(fields=['patient', '-created_at'], name='patients_me_patient_2d9b89_idx'), models.Index(fields=['is_critical'], name='patients_me_is_crit_d962d9_idx')],
            },
        ),
    ]
