# Generated by Django 5.0.6 on 2026-08-30 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basins', '0001_initial'),
        ('patients', '0002_medicalfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='basin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='basins.basin', verbose_name='الحوض الصحي'),
        ),
    ]
