# Generated by Django 5.0.6 on 2026-08-31 06:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_channel_basin'),
        ('patients', '0003_patient_basin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='اسم الدواء')),
                ('dosage', models.CharField(help_text='مثال: 500 ملغ، قرص واحد', max_length=100, verbose_name='الجرعة')),
                ('dose_times', models.CharField(default='08:00', help_text='مواعيد الجرعات مفصولة بفواصل بصيغة HH:MM — مثال: 08:00,14:00,20:00', max_length=255, verbose_name='أوقات الجرعات')),
                ('start_date', models.DateField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('instructions', models.TextField(blank=True, verbose_name='التعليمات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medications', to='channels.channel', verbose_name='القناة')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='patients.patient', verbose_name='المريض')),
                ('prescribed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescribed_medications', to=settings.AUTH_USER_MODEL, verbose_name='الطبيب الواصف')),
            ],
            options={
                'verbose_name': 'دواء',
                'verbose_name_plural': 'الأدوية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_for', models.DateTimeField(verbose_name='موعد الجرعة')),
                ('status', models.CharField(choices=[('TAKEN', 'تم تناوله'), ('SKIPPED', 'تم تخطيه'), ('MISSED', 'فائت')], default='TAKEN', max_length=10, verbose_name='الحالة')),
                ('taken_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت التناول الفعلي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='patients.medication', verbose_name='الدواء')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_logs', to=settings.AUTH_USER_MODEL, verbose_name='سجله')),
            ],
            options={
                'verbose_name': 'سجل جرعة',
                'verbose_name_plural': 'سجلات الجرعات',
                'ordering': ['-scheduled_for'],
            },
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['patient', 'is_active'], name='patients_me_patient_64d68f_idx'),
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['is_active', 'start_date'], name='patients_me_is_acti_ffbed3_idx'),
        ),
        migrations.AddConstraint(
            model_name='medicationlog',
            constraint=models.UniqueConstraint(fields=('medication', 'scheduled_for'), name='unique_medication_scheduled_dose'),
        ),
    ]
