# Generated by Django 5.0.14 on 2026-09-09 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_created_at_index'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='patient',
            new_name='patients_pa_basin_i_0a03a3_idx',
            old_name='patient_basin_created_idx',
        ),
        migrations.RenameIndex(
            model_name='patient',
            new_name='patients_pa_created_15d2a5_idx',
            old_name='patient_created_idx',
        ),
    ]
