# Generated by Django 5.0.14 on 2026-09-04 20:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=50, verbose_name='رقم الغرفة')),
                ('room_type', models.CharField(choices=[('GENERAL', 'عامة'), ('PRIVATE', 'خاصة'), ('ISOLATION', 'عزل'), ('ICU', 'عناية مركزة'), ('VIP', 'VIP')], default='GENERAL', max_length=20, verbose_name='نوع الغرفة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'غرفة',
                'verbose_name_plural': 'الغرف',
                'ordering': ['ward', 'room_number'],
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم الجناح')),
                ('floor', models.CharField(blank=True, max_length=50, verbose_name='الطابق')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'جناح',
                'verbose_name_plural': 'الأجنحة',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bed_number', models.CharField(max_length=50, verbose_name='رقم السرير')),
                ('status', models.CharField(choices=[('FREE', 'متاح'), ('OCCUPIED', 'مشغول'), ('MAINTENANCE', 'صيانة'), ('CLEANING', 'قيد التنظيف'), ('RESERVED', 'محجوز')], default='FREE', max_length=20, verbose_name='حالة السرير')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='wards.room', verbose_name='الغرفة')),
            ],
            options={
                'verbose_name': 'سرير',
                'verbose_name_plural': 'الأسرّة',
                'ordering': ['room', 'bed_number'],
                'unique_together': {('room', 'bed_number')},
            },
        ),
        migrations.AddField(
            model_name='room',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='wards.ward', verbose_name='الجناح'),
        ),
        migrations.CreateModel(
            name='BedAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admission_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ ووقت الدخول')),
                ('discharge_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ ووقت الخروج')),
                ('diagnosis_on_admission', models.TextField(blank=True, verbose_name='التشخيص عند الدخول')),
                ('is_active', models.BooleanField(default=True, verbose_name='حالي/نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions_created', to=settings.AUTH_USER_MODEL, verbose_name='موظف الدخول')),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='wards.bed', verbose_name='السرير')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bed_assignments', to='patients.patient', verbose_name='المريض')),
            ],
            options={
                'verbose_name': 'تخصيص سرير (دخول مريض)',
                'verbose_name_plural': 'تخصيص الأسرّة',
                'ordering': ['-admission_date'],
                'indexes': [models.Index(fields=['patient', 'is_active'], name='wards_bedas_patient_afcee3_idx'), models.Index(fields=['bed', 'is_active'], name='wards_bedas_bed_id_57da8f_idx')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('ward', 'room_number')},
        ),
    ]
