# Generated by Django 5.0.6 on 2026-08-28 03:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('full_name', models.CharField(max_length=255, verbose_name='الاسم الكامل')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='الهاتف')),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'مدير النظام'), ('HOSPITAL_ADMIN', 'مدير المستشفى'), ('DOCTOR', 'طبيب'), ('NURSE', 'ممرض/ممرضة'), ('LAB_TECH', 'فني مختبر'), ('PHARMACIST', 'صيدلي'), ('AUDITOR', 'مراجع أمني'), ('PATIENT', 'مريض')], default='PATIENT', max_length=20, verbose_name='الدور')),
                ('license_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الترخيص الطبي')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='القسم')),
                ('specialization', models.CharField(blank=True, max_length=100, verbose_name='التخصص')),
                ('is_biometric_enabled', models.BooleanField(default=False, verbose_name='المصادقة البيومترية مفعلة')),
                ('biometric_enrolled_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('failed_login_attempts', models.PositiveIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('mfa_secret', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمون',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BiometricChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('challenge', models.TextField(verbose_name='التحدي')),
                ('expected_response', models.TextField(verbose_name='الرد المتوقع المشفر')),
                ('expires_at', models.DateTimeField(verbose_name='تنتهي في')),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'used', 'expires_at'], name='accounts_bi_user_id_a088a5_idx')],
            },
        ),
        migrations.CreateModel(
            name='BiometricProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=255, verbose_name='معرف الجهاز')),
                ('device_name', models.CharField(blank=True, max_length=255, verbose_name='اسم الجهاز')),
                ('platform', models.CharField(choices=[('ANDROID', 'Android'), ('IOS', 'iOS'), ('WEB', 'Web')], max_length=20, verbose_name='المنصة')),
                ('biometric_hash', models.TextField(verbose_name='الهاش البيوميتري المشفر')),
                ('salt', models.CharField(max_length=64, verbose_name='الملح')),
                ('public_key', models.TextField(blank=True, verbose_name='المفتاح العام')),
                ('private_key_encrypted', models.TextField(blank=True, verbose_name='المفتاح الخاص المشفر')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('failed_attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_profiles', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'الملف البيوميتري',
                'verbose_name_plural': 'الملفات البيومترية',
                'indexes': [models.Index(fields=['user', 'device_id'], name='accounts_bi_user_id_55ef4c_idx'), models.Index(fields=['is_active'], name='accounts_bi_is_acti_7d9535_idx')],
                'unique_together': {('user', 'device_id')},
            },
        ),
    ]
