# Generated by Django 5.0.6 on 2026-09-01 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('basins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='basin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='basins.basin', verbose_name='الحوض الصحي'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='biometricchallenge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='biometricprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_profiles', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddIndex(
            model_name='biometricchallenge',
            index=models.Index(fields=['user', 'used', 'expires_at'], name='accounts_bi_user_id_a088a5_idx'),
        ),
        migrations.AddIndex(
            model_name='biometricprofile',
            index=models.Index(fields=['user', 'device_id'], name='accounts_bi_user_id_55ef4c_idx'),
        ),
        migrations.AddIndex(
            model_name='biometricprofile',
            index=models.Index(fields=['is_active'], name='accounts_bi_is_acti_7d9535_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='biometricprofile',
            unique_together={('user', 'device_id')},
        ),
    ]
