# Generated by Django 5.0.6 on 2026-08-30 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_mfa_created_at_user_mfa_enabled'),
        ('basins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='basin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='basins.basin', verbose_name='الحوض الصحي'),
        ),
    ]
