# Generated by Django 5.0.6 on 2026-09-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP INDEX IF EXISTS accounts_user_full_name_f0cb7590;",
            reverse_sql=""
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='الاسم الكامل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'مدير النظام'), ('HOSPITAL_ADMIN', 'مدير المستشفى'), ('DOCTOR', 'طبيب'), ('NURSE', 'ممرض/ممرضة'), ('LAB_TECH', 'فني مختبر'), ('PHARMACIST', 'صيدلي'), ('AUDITOR', 'مراجع أمني'), ('PATIENT', 'مريض')], db_index=True, default='PATIENT', max_length=20, verbose_name='الدور'),
        ),
    ]
