# Generated by Django 5.0.6 on 2026-09-03 07:08

from django.db import migrations, models


def drop_existing_indexes(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("""
            DO $$
            DECLARE
                r RECORD;
            BEGIN
                FOR r IN (
                    SELECT i.relname AS index_name
                    FROM pg_class t,
                         pg_class i,
                         pg_index ix,
                         pg_attribute a
                    WHERE t.oid = ix.indrelid
                      AND i.oid = ix.indexrelid
                      AND a.attrelid = t.oid
                      AND a.attnum = ANY(ix.indkey)
                      AND t.relkind = 'r'
                      AND t.relname = 'accounts_user'
                      AND a.attname IN ('full_name', 'role')
                ) LOOP
                    EXECUTE 'DROP INDEX IF EXISTS ' || r.index_name || ' CASCADE;';
                END LOOP;
            END $$;
            """)

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(drop_existing_indexes, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='الاسم الكامل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'مدير النظام'), ('HOSPITAL_ADMIN', 'مدير المستشفى'), ('DOCTOR', 'طبيب'), ('NURSE', 'ممرض/ممرضة'), ('LAB_TECH', 'فني مختبر'), ('PHARMACIST', 'صيدلي'), ('AUDITOR', 'مراجع أمني'), ('PATIENT', 'مريض')], db_index=True, default='PATIENT', max_length=20, verbose_name='الدور'),
        ),
    ]
