# Generated by Django 5.0.6 on 2026-09-01 10:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_basin'),
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('success', models.BooleanField(db_index=True, default=False, help_text='Whether the login attempt was successful')),
                ('failure_reason', models.CharField(blank=True, choices=[('INVALID_EMAIL', 'Email not found'), ('INVALID_PASSWORD', 'Wrong password'), ('ACCOUNT_LOCKED', 'Account locked'), ('ACCOUNT_DISABLED', 'Account disabled'), ('MFA_REQUIRED', 'MFA verification required'), ('MFA_FAILED', 'MFA verification failed'), ('BIOMETRIC_FAILED', 'Biometric verification failed'), ('DEVICE_BLACKLISTED', 'Device blacklisted'), ('SUSPICIOUS_ACTIVITY', 'Suspicious activity detected'), ('RATE_LIMITED', 'Rate limit exceeded')], help_text='Reason for failure (if applicable)', max_length=100, null=True)),
                ('mac_address', models.CharField(blank=True, db_index=True, help_text='MAC address (critical forensic evidence)', max_length=17, null=True)),
                ('ip_address', models.GenericIPAddressField(db_index=True, help_text='Client IP address')),
                ('user_agent', models.TextField(blank=True, help_text='User-Agent string', null=True)),
                ('platform', models.CharField(blank=True, help_text='Operating system platform', max_length=100, null=True)),
                ('browser', models.CharField(blank=True, help_text='Browser name', max_length=100, null=True)),
                ('screen_resolution', models.CharField(blank=True, help_text='Screen resolution', max_length=20, null=True)),
                ('browser_timezone', models.CharField(blank=True, help_text='Browser timezone', max_length=50, null=True)),
                ('language', models.CharField(blank=True, help_text='Browser language', max_length=20, null=True)),
                ('canvas_fingerprint', models.CharField(blank=True, help_text='Canvas fingerprint hash', max_length=64, null=True)),
                ('webrtc_ip', models.GenericIPAddressField(blank=True, help_text='WebRTC leaked IP', null=True)),
                ('tls_fingerprint', models.CharField(blank=True, help_text='TLS fingerprint (JA3)', max_length=64, null=True)),
                ('auth_method', models.CharField(choices=[('PASSWORD', 'Password'), ('MFA', 'Multi-Factor Authentication'), ('BIOMETRIC', 'Biometric'), ('RECOVERY', 'Recovery Code')], help_text='Authentication method used', max_length=50)),
                ('email_attempted', models.EmailField(blank=True, db_index=True, help_text='Email address used in login attempt', max_length=254, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the attempt occurred')),
                ('risk_score', models.PositiveSmallIntegerField(default=0, help_text='Risk score 0-100 (calculated based on various factors)')),
                ('risk_factors', models.JSONField(blank=True, default=list, help_text='List of risk factors detected')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the login attempt')),
                ('device_fingerprint', models.ForeignKey(blank=True, help_text='Associated device fingerprint', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_attempts', to='security.devicefingerprint')),
                ('user', models.ForeignKey(blank=True, help_text='User account (if authentication reached this stage)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login Attempt',
                'verbose_name_plural': 'Login Attempts',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['success', '-timestamp'], name='accounts_lo_success_472f8a_idx'), models.Index(fields=['ip_address', '-timestamp'], name='accounts_lo_ip_addr_eed231_idx'), models.Index(fields=['mac_address'], name='accounts_lo_mac_add_0ca4ae_idx'), models.Index(fields=['email_attempted', '-timestamp'], name='accounts_lo_email_a_e40c4c_idx'), models.Index(fields=['user', '-timestamp'], name='accounts_lo_user_id_6a9788_idx'), models.Index(fields=['auth_method'], name='accounts_lo_auth_me_7d49f1_idx'), models.Index(fields=['risk_score'], name='accounts_lo_risk_sc_89ee7a_idx')],
            },
        ),
    ]
