# Generated by Django 5.0.6 on 2026-09-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_full_name_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'مدير النظام'), ('HOSPITAL_ADMIN', 'مدير المستشفى'), ('CENTER_ADMIN', 'مدير مركز'), ('DOCTOR', 'طبيب'), ('NURSE', 'ممرض/ممرضة'), ('LAB_TECH', 'فني مختبر'), ('PHARMACIST', 'صيدلي'), ('AUDITOR', 'مراجع أمني'), ('PATIENT', 'مريض'), ('ACCOUNTANT', 'محاسب'), ('RECEPTIONIST', 'موظف استقبال')], db_index=True, default='PATIENT', max_length=20, verbose_name='الدور'),
        ),
    ]
