# Generated by Django 5.0.14 on 2026-09-11 16:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_biometric_public_key_credentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'مدير النظام'), ('HOSPITAL_ADMIN', 'مدير المستشفى'), ('CENTER_ADMIN', 'مدير مركز'), ('DOCTOR', 'طبيب'), ('NURSE', 'ممرض/ممرضة'), ('LAB_TECH', 'فني مختبر'), ('PHARMACIST', 'صيدلي'), ('AUDITOR', 'مراجع أمني'), ('PATIENT', 'مريض'), ('ACCOUNTANT', 'محاسب'), ('RECEPTIONIST', 'موظف استقبال')], db_index=True, max_length=20, verbose_name='الدور')),
                ('permission', models.CharField(db_index=True, max_length=100, verbose_name='الصلاحية')),
                ('allowed', models.BooleanField(default=True, verbose_name='مسموح')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_permission_changes', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'صلاحية دور',
                'verbose_name_plural': 'صلاحيات الأدوار',
                'ordering': ['role', 'permission'],
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
