# Generated by Django 5.0.6 on 2026-08-30 22:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255, unique=True, verbose_name='اسم الملف')),
                ('filepath', models.CharField(max_length=500, verbose_name='المسار')),
                ('size_bytes', models.BigIntegerField(default=0, verbose_name='الحجم (بايت)')),
                ('checksum', models.CharField(blank=True, max_length=64, verbose_name='بصمة SHA-256')),
                ('status', models.CharField(choices=[('COMPLETED', 'مكتمل'), ('FAILED', 'فاشل')], default='COMPLETED', max_length=10, verbose_name='الحالة')),
                ('kind', models.CharField(choices=[('MANUAL', 'يدوي'), ('SCHEDULED', 'مجدول')], default='MANUAL', max_length=10, verbose_name='النوع')),
                ('row_counts', models.JSONField(blank=True, default=dict, verbose_name='عدد السجلات')),
                ('media_files', models.PositiveIntegerField(default=0, verbose_name='عدد الملفات المرفقة')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='المدة (مللي ثانية)')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='ملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_backups', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'نسخة احتياطية',
                'verbose_name_plural': 'النسخ الاحتياطية',
                'ordering': ['-created_at'],
            },
        ),
    ]
