# Generated by Django 5.0.14 on 2026-09-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0002_setup_periodic_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='backuprecord',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت التسليم'),
        ),
        migrations.AddField(
            model_name='backuprecord',
            name='delivery_detail',
            field=models.JSONField(blank=True, default=dict, help_text='نتيجة كل قناة تسليم، مثل {"telegram": {...}, "cloud": {...}}', verbose_name='تفاصيل التسليم'),
        ),
        migrations.AddField(
            model_name='backuprecord',
            name='delivery_status',
            field=models.CharField(choices=[('NOT_SENT', 'لم تُرسل'), ('TELEGRAM', 'أُرسلت عبر تلجرام'), ('CLOUD', 'أُرسلت للتخزين السحابي'), ('BOTH', 'تلجرام + سحابي'), ('DELIVERY_FAILED', 'فشل التسليم الخارجي')], db_index=True, default='NOT_SENT', max_length=20, verbose_name='التسليم الخارجي'),
        ),
        migrations.AddField(
            model_name='backuprecord',
            name='offsite_key',
            field=models.CharField(blank=True, max_length=500, verbose_name='مفتاح النسخة في التخزين السحابي'),
        ),
    ]
