# Generated by Django 5.0.14 on 2026-09-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0003_backup_offsite_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='backuprecord',
            name='scope',
            field=models.CharField(choices=[('FULL', 'كامل (قاعدة + ملفات)'), ('DATABASE', 'قاعدة البيانات فقط'), ('MEDIA', 'الملفات المرفوعة فقط')], db_index=True, default='FULL', max_length=10, verbose_name='النطاق'),
        ),
    ]
