# Generated by Django 5.0.6 on 2026-09-01 20:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='اسم الدواء')),
                ('scientific_name', models.CharField(blank=True, max_length=255, verbose_name='الاسم العلمي')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='الباركود')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='الكمية المتوفرة')),
                ('reorder_level', models.PositiveIntegerField(default=10, verbose_name='حد إعادة الطلب')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='سعر الوحدة')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('instructions', models.TextField(blank=True, verbose_name='تعليمات عامة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'دواء',
                'verbose_name_plural': 'الأدوية',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('diagnosis_code', models.CharField(blank=True, max_length=50, verbose_name='رمز التشخيص ICD-10')),
                ('digital_signature', models.TextField(blank=True, help_text='توقيع مشفر يثبت صحة الوصفة', verbose_name='التوقيع الرقمي')),
                ('is_signed', models.BooleanField(default=False, verbose_name='موقعة إلكترونياً')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التوقيع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات الصيدلي')),
                ('status', models.CharField(choices=[('ISSUED', 'مصدرة'), ('DISPENSED', 'مصروفة'), ('CANCELLED', 'ملغاة')], default='ISSUED', max_length=50, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions_issued', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.patient')),
            ],
            options={
                'verbose_name': 'وصفة طبية',
                'verbose_name_plural': 'الوصفات الطبية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dosage', models.CharField(max_length=255, verbose_name='الجرعة')),
                ('frequency', models.CharField(max_length=255, verbose_name='التكرار')),
                ('duration_days', models.PositiveIntegerField(default=1, verbose_name='المدة (أيام)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية المطلوبة')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacy.medication')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='DrugInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('MILD', 'خفيف'), ('MODERATE', 'متوسط'), ('SEVERE', 'خطير')], default='MODERATE', max_length=50, verbose_name='الخطورة')),
                ('description', models.TextField(verbose_name='وصف التداخل')),
                ('drug_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_a', to='pharmacy.medication')),
                ('drug_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_b', to='pharmacy.medication')),
            ],
            options={
                'verbose_name': 'تداخل دوائي',
                'verbose_name_plural': 'التداخلات الدوائية',
                'unique_together': {('drug_a', 'drug_b')},
            },
        ),
    ]
