# Generated by Django 5.0.14 on 2026-09-08 16:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_channels', '0002_initial'),
        ('patients', '0002_patient_user'),
        ('pharmacy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('_name', models.TextField(db_column='name', verbose_name='اسم الدواء المشفر')),
                ('dosage', models.CharField(max_length=255, verbose_name='الجرعة')),
                ('times', models.JSONField(default=list, verbose_name='أوقات الجرعات')),
                ('start_date', models.DateField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('instructions', models.TextField(blank=True, verbose_name='تعليمات')),
                ('schedule_type', models.CharField(choices=[('DAILY', 'يومي'), ('WEEKLY', 'أسبوعي'), ('AS_NEEDED', 'عند الحاجة')], default='DAILY', max_length=20, verbose_name='نمط الجدولة')),
                ('source_id', models.UUIDField(blank=True, db_index=True, help_text='معرّف الخطة المحلية على جهاز العميل لمنع التكرار', null=True, verbose_name='معرف المصدر')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_plans', to='app_channels.channel', verbose_name='القناة')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medication_plans', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_plans', to='patients.patient', verbose_name='المريض')),
            ],
            options={
                'verbose_name': 'خطة دواء',
                'verbose_name_plural': 'خطط الأدوية',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'is_active'], name='pharmacy_me_patient_9c15e7_idx'), models.Index(fields=['created_by', '-created_at'], name='pharmacy_me_created_e0e900_idx')],
            },
        ),
    ]
