# Generated by Django 5.0.14 on 2026-09-04 20:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت الجلسة المجدول')),
                ('status', models.CharField(choices=[('SCHEDULED', 'مجدول'), ('IN_PROGRESS', 'قيد التقدم'), ('COMPLETED', 'مكتمل'), ('CANCELLED', 'ملغى')], default='SCHEDULED', max_length=20, verbose_name='الحالة')),
                ('room_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True, verbose_name='معرف الغرفة')),
                ('join_url', models.URLField(blank=True, verbose_name='رابط الانضمام')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات الطبيب')),
                ('diagnosis', models.TextField(blank=True, verbose_name='التشخيص المبدئي')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation', to='appointments.appointment', verbose_name='الموعد المرتبط')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultations', to=settings.AUTH_USER_MODEL, verbose_name='الطبيب')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='patients.patient', verbose_name='المريض')),
            ],
            options={
                'verbose_name': 'جلسة استشارة عن بعد',
                'verbose_name_plural': 'جلسات الاستشارة عن بعد',
                'ordering': ['-scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='telemedicine/attachments/', verbose_name='مرفق')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='المرسل')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='telemedicine.consultation', verbose_name='الاستشارة')),
            ],
            options={
                'verbose_name': 'رسالة دردشة',
                'verbose_name_plural': 'رسائل الدردشة',
                'ordering': ['created_at'],
            },
        ),
    ]
