# Generated by Django 5.0.14 on 2026-09-09 18:45

import apps.telemedicine.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemedicine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='telemedicine/attachments/', validators=[apps.telemedicine.models.validate_chat_attachment], verbose_name='مرفق'),
        ),
    ]
